theme: jekyll-theme-tactile 
title: Corionis Service Manager 
description: Monitor & manage selected Windows services 
show_downloads: true 
excerpt_separator: thisnevermatchme 
version: 1.0.1.174
